name: movie_mania
description: A movie app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  sizer: ^2.0.15
  get_it: ^7.6.0
  injectable: ^2.1.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  dropdown_button2: ^1.9.1
  optimized_cached_image: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner:
  json_serializable:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/appLogo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
